# Generated by Django 5.2.1 on 2025-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Super Admin', 'Super Admin'), ('User', 'User')], max_length=20, null=True),
        ),
    ]
